### ISSUE TITLE
Upload latest version to PyPi

### ISSUE THREAD

**Issue by LordFlashmeow** [leonhard-s/auraxium#12]
The latest version on PyPi was uploaded on October 16, 2019. Do you have the ability to upload the latest version, with the bugfixes we've made?

**Comment by leonhard-s** [comment]
Certainly, I'll get on that after work.

Should we set up an action that auto-publishes it in sync with master once a day? We'd have to lock down the branch perms a bit/give you guys permission to push master.

**Comment by LordFlashmeow** [comment]
I see a couple of options moving forward:
1. Auto-publish master once a day, requires changing permissions for pushing
2. Start using releases, and trigger an update to PyPi on new release
3. (possibly in conjunction with 2) Keep master as the release branch, and create other branches that we can push to for new features. You would be in control of master, and we would make PRs on branches. This would ensure that master is always functional and prevent merge conflicts.

**Comment by leonhard-s** [comment]
I opted for a mix of 2 and 3 - master should always be a working version in case users wish to install from source (for those sweet, sweet bugfixes).
PyPI pushes will be triggered on releases, `master` should always be a working version so users can install from source if needed. It is also where others branch off to implement their features or fixes, it should not have to be tied to a (pseudo)-release.
