### ISSUE TITLE
[BUG] Methods and fields with the same iname in query.py and join.py

### ISSUE THREAD

**Issue by qcoumes** [leonhard-s/auraxium#3]
In `auraxium/query.py`, `__init__()` method create two arrays `hide_fields` and `show_fields` to store the fields given to the methods `hide_fields()` and `show_fields()`.

Since the arrays and the methods have the same name, the arrays overwrite the methods, causing a `TypeError: 'list' object is not callable` when trying to call the methods.

The same happens in `auraxium/join.py` with both the arrays and the methods called `hide` and `show`.

**Comment by qcoumes** [comment]
I'll do a pull request with a fix soon

**Comment by leonhard-s** [comment]
Resolved by #6.
