### ISSUE TITLE
[BUG] Wrong separator for inner joins

### ISSUE THREAD

**Issue by qcoumes** [leonhard-s/auraxium#4]
**Describe the bug**
Inner joins are currently all separated with parenthesis: `c:join=join1(join1a)(join1b)`

**Expected behavior**
Inner joins should be separated with a comma : `c:join=join1(join1a, join1b)`

**Comment by qcoumes** [comment]
I'll do a pull request with a fix soon

**Comment by leonhard-s** [comment]
Interestingly, both of these options work. I agree that the latter is more readable though - plus it's also the intended syntax to use.
