### ISSUE TITLE
Faction image_path missing

### ISSUE THREAD

**Issue by dbrennand** [leonhard-s/auraxium#47]
Hi there👋🏻 

In the tests API response for [`faction.json`](https://github.com/leonhard-s/auraxium/blob/master/tests/data/rest/datatype_payloads/faction.json) I can see that `image_path` should be present however, I'm not receiving a value for it from the API.

Can anyone replicate this?

My code:

```
    async with auraxium.Client() as client:
        # Get Character object
        player = await client.get_by_name(auraxium.ps2.Character, "Player")
        faction = await player.faction()
        print(faction.data)
        # image_path is not present in the data.
```

The response data missing `image_path`:
```
faction_id=1 name=LocaleData(de='Vanu-Souveränität', en='Vanu Sovereignty', es='Soberanía Vanu', fr='Souveraineté Vanu', it='Sovranità Vanu') code_tag='VS' user_selectable=True
```

**Comment by leonhard-s** [comment]
Hi, thanks for the report!

Can confirm, these fields are currently missing. These image-specific fields are defined in a separate mix-in class, whose fields are not being added properly.
This is a regression introduced when I switched from Python dataclasses to pydantic models.

I started a PR that should resolve this, should be a quick fix.
