### ISSUE TITLE
outfit.leader() -> Character or OutfitMember

### ISSUE THREAD

**Issue by dbrennand** [leonhard-s/auraxium#49]
Hi again 👋🏻 

I'm using the [outfit.leader()](https://auraxium.readthedocs.io/en/latest/api/ps2.html#auraxium.ps2.Outfit.leader) classmethod expecting to get the outfit leader's character data. The documentation says the object returned is `Character`:

![image](https://user-images.githubusercontent.com/52419383/117416303-2087af00-af11-11eb-9bf9-dc3310278a3d.png)

But looking at the response it looks more like [`OutfitMember`](https://github.com/leonhard-s/auraxium/blob/master/tests/data/rest/datatype_payloads/outfit_member.json).

EDIT: Removed second issue, user error.

**Comment by dbrennand** [comment]
Oh my goodness, Forget the second issue. I forgot to `await` 🤦🏻

**Comment by leonhard-s** [comment]
Hi - that looks like a documentation error, the implementation does correctly type it as an `OutfitMember` instance.
I pushed a correction, might take a few minutes for ReadTheDocs to update accordingly.

Thank you for the report - the new documentation system makes for pretty docs, but it does come with some extra steps that are hard to check in bulk. 👍
