### ISSUE TITLE
[BUG] Wrong separator for hide and show fields in a join

### ISSUE THREAD

**Issue by qcoumes** [leonhard-s/auraxium#5]
**Describe the bug**
Fields are currently separated with a comma `c:join=join1^hide:a,b^show:c,d`

**Expected behavior**
Fields must be separated with single quote `c:join=join1^hide:a'b^show:c'd`

**Comment by qcoumes** [comment]
I'll do a pull request with a fix soon

**Comment by leonhard-s** [comment]
Fixed by e31e7bb2.
