### ISSUE TITLE
RTD broken link

### ISSUE THREAD

**Issue by Vuks69** [leonhard-s/auraxium#54]
[On readthedocs "Getting started" page](https://auraxium.readthedocs.io/en/latest/usage/basic/getting-started.html#service-ids) there is a Service ID application form (https://auraxium.readthedocs.io/en/latest/usage/basic/serviceIDsignup) - the link is broken/doesn't exist.

**Comment by leonhard-s** [comment]
Thanks for the heads-up, the typo should be fixed on RTD any minute. 👍
