### ISSUE TITLE
Client.get_by_name not using name.first_lower

### ISSUE THREAD

**Issue by yakMM** [leonhard-s/auraxium#61]
Hello,

For the character collection, is there a reason `Client.get_by_name` is using a query with `case(False)` on `name.first` instead of a simple query on `name.first_lower`: 

https://github.com/leonhard-s/auraxium/blob/145470755c2136366ba6cfe7a9003eda3772ab6a/auraxium/_client.py#L197

While the docstring for `case` mentions that _case-insensitive look-ups are significantly slower_ and should be avoided when possible, citing the character collection as an example?
https://github.com/leonhard-s/auraxium/blob/145470755c2136366ba6cfe7a9003eda3772ab6a/auraxium/census/_query.py#L299

**Comment by leonhard-s** [comment]
Hi, thanks for the report - good catch.

The PS2 datatypes themselves had (now deprecated) overrides that would handle these optimizations, but these will be removed to remove redundancy and clean up the syntax. However, given that there already is a special case to handle the non-standard field name, replacing it with `name.first_lower` is a quick fix.

**Comment by yakMM** [comment]
Yes, I asked because it is already a special case, otherwise the argument of genericity would prevail

**Comment by leonhard-s** [comment]
Fixed in 0.2.3
