### ISSUE TITLE
Ignoring Unsupported Payload (Continent Lock)

### ISSUE THREAD

**Issue by LCWilliams** [leonhard-s/auraxium#62]
## Pre Checks:
 - Ensured updated library (`pipenv update`)

## Console Output
```Ignoring unsupported payload: {'event_name': 'ContinentLock', 'metagame_event_id': '0', 'nc_population': '0', 'previous_faction': '0', 'timestamp': '1677767068', 'tr_population': '0', 'triggering_faction': '1', 'vs_population': '100', 'world_id': '13', 'zone_id': '238289260'}```

**Comment by leonhard-s** [comment]
Confirmed, this field is no longer being sent by the ESS.
