### ISSUE TITLE
events.ContinentUnlock no longer exists

### ISSUE THREAD

**Issue by wupasscat** [leonhard-s/auraxium#65]
![image](https://user-images.githubusercontent.com/26749803/235014429-7c1fbd0b-2f1a-4b70-983d-78f0ab8ce673.png)
https://discord.com/channels/1019343142471880775/1019509468754608168/1101292366809268294

**Comment by leonhard-s** [comment]
Hi, thanks for the report. I am aware that the documentation is out of date in places, a project is underway to update the Auraxium Docs and make them more maintainable via the API spec in https://github.com/leonhard-s/ps2-api-docs. Soon:tm:
